#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

APP_DIR="${TRIM_APPDEST}"
APP_DATA_DIR="${TRIM_PKGVAR}"

# Allow our custom distributor in addition to upstream conversun
export ALLOWED_DISTRIBUTORS="conversun,soleo,Sole0nce"

SERVICE_COMMAND="$APP_DIR/store-server"
SVC_BACKGROUND=y
SVC_WRITE_PID=y
